# apt-get if using the trusty build environment.
sudo: required
dist: trusty

language: cpp

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

#install:

script:
  -make -j4
