sudo: required
dist: trusty

language: cpp

compiler: gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

#install:

script:
  - echo 'Building with -j4'
  - make -j4